'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ml';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        // Load language from localStorage on mount (client-side only)
        if (typeof window !== 'undefined') {
            const savedLanguage = localStorage.getItem('language') as Language;
            if (savedLanguage) {
                setLanguageState(savedLanguage);
            }
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', lang);
            document.documentElement.lang = lang; // Update html tag attribute
        }
    };

    useEffect(() => {
        // Sync initial language to html tag
        if (typeof window !== 'undefined' && language) {
            document.documentElement.lang = language;
        }
    }, [language]);

    const t = (key: string): string => {
        const keys = key.split('.');
        let value: any = language === 'ml' ? mlTranslations : enTranslations;

        for (const k of keys) {
            value = value?.[k];
            if (value === undefined) {
                return key; // Return key if translation not found
            }
        }

        return value || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

// English Translations
const enTranslations = {
    nav: {
        home: 'Home',
        massTimings: 'Mass Timings',
        services: 'Services',
        community: 'Community',
        about: 'About',
        contact: 'Contact',
        prayerRequest: 'Prayer Request',
        thanksgiving: 'Thanksgiving',
        venda: 'Venda (Offerings)',
        bloodBank: 'Blood Bank',
        familyUnits: 'Family Directory',
        gallery: 'Gallery',
        documents: 'Documents',
        brandName: 'St Mary\'s Church',
    },
    home: {
        heroTitle: 'St Mary\'s Jacobite Syrian Church',
        heroSubtitle: 'Malayidomthuruth',
        bibleVerse1: '"For God so loved the world" - John 3:16',
        bibleVerse2: '"I am the way, the truth, and the life" - John 14:6',
        bibleVerse3: '"Love one another as I have loved you" - John 13:34',
        quickLinksTitle: 'Quick Links',
        prayerRequestTitle: 'Prayer Request',
        prayerRequestDesc: 'Submit your prayer intentions and we will pray for you',
        thanksgivingTitle: 'Thanksgiving',
        thanksgivingDesc: 'Share your blessings and thanksgiving with our community',
        vendaTitle: 'Venda (Offerings)',
        vendaDesc: 'Support our parish through your generous offerings',
        latestNewsTitle: 'Latest News',
        managingCommitteeTitle: 'Managing Committee',
        ourChurchesTitle: 'Our Churches',
        ourServicesTitle: 'Our Services',
        latestAnnouncementsTitle: 'Latest Announcements',
        joinCommunityTitle: 'Join Our Community',
        joinCommunityDesc: 'Be part of our loving parish family. Connect with us today!',
        holyMassTitle: 'Holy Mass',
        holyMassDesc: 'Daily and Sunday mass timings',
        bloodBankTitle: 'Blood Bank',
        bloodBankDesc: 'Register as a blood donor',
        galleryTitle: 'Gallery',
        galleryDesc: 'View our church events and activities',
        familyUnitsTitle: 'Family Directory',
        familyUnitsDesc: 'Parish family directory',
        loadingChurches: 'Loading churches...',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
    },
    buttons: {
        submitRequest: 'Submit Request',
        shareThanksgiving: 'Share Thanksgiving',
        makeOffering: 'Make Offering',
        learnMore: 'Learn More',
        viewSchedule: 'View Schedule',
        registerNow: 'Register Now',
        viewGallery: 'View Gallery',
        viewDirectory: 'View Directory',
        viewAllAnnouncements: 'View All Announcements',
        contactUs: 'Contact Us',
        submit: 'Submit',
        cancel: 'Cancel',
    },
    about: {
        title: 'About Our Parish',
        ourHistory: 'Our History',
        ourMission: 'Our Mission',
        ourVision: 'Our Vision',
        ourChurches: 'Our Churches',
        ourTeam: 'Our Team',
        heroSubtitle: 'Serving our community with faith, hope, and love since 1950',
        storyPara1: 'Our parish was founded in 1950 with a vision to create a welcoming community where people could grow in their faith and serve others. Over the decades, we have grown from a small gathering to a vibrant community of believers dedicated to worship, fellowship, and outreach.',
        storyPara2: 'Today, we continue to honor our heritage while embracing new ways to serve our community and share the love of Christ with all who enter our doors.',
        joinUsSunday: 'Join Us This Sunday',
        experienceWorship: 'Experience worship, fellowship, and community with us!',
        backToHome: 'Back to Home',
    },
    contact: {
        title: 'Contact Us',
        getInTouch: 'Get in Touch',
        heroSubtitle: 'We\'d love to hear from you. Reach out to our parish community!',
        introText: 'Feel free to reach out to us through any of the following methods. We\'re here to serve you!',
        mainChurchAddress: 'Main Church Address',
        officeHours: 'Office Hours',
        massTimings: 'Mass Timings',
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        message: 'Message',
        subject: 'Subject',
        send: 'Send Message',
        sending: 'Sending...',
        sendMessageBtn: '✉️ Send Message',
        thankYouMessage: 'Thank you for your message! We\'ll get back to you soon.',
        fillAllFields: 'Please fill in all fields',
        validEmail: 'Please enter a valid email address',
        submitFailed: 'Failed to submit form. Please try again.',
        yourFullName: 'Your full name',
        yourEmail: 'your.email@example.com',
        whatRegarding: 'What is this regarding?',
        typeMessage: 'Type your message here...',
        findUsMap: 'Find Us on the Map',
        visitUs: 'Visit us at our main church location in Kochi, Kerala',
        mapNotLoading: 'Map not loading? This might be due to ad blockers.',
        openGoogleMaps: 'Open in Google Maps',
        otherChurches: 'Our Other Churches',
        address: 'Address',
        sundayMass: 'Sunday Mass',
        office: 'Office',
        father: 'Father',
        emergency: 'Emergency',
        mondayFriday: 'Monday - Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
        closedMassTimes: 'Closed (Mass times only)',
        lunchBreak: 'Lunch Break',
        weekdays: 'Weekdays',
        sundays: 'Sundays',
        viewAllTimings: 'View All Timings',
        sendUsMessage: 'Send Us a Message',
    },
    massTimings: {
        title: 'Mass Timings',
        subtitle: 'Join us for Holy Eucharist celebration at our parish churches',
        selectChurch: 'Select Church',
        allChurches: 'All Churches',
        day: 'Day',
        time: 'Time',
        language: 'Language',
        type: 'Type',
        allMasses: 'All Masses',
        sundays: 'Sundays',
        weekdays: 'Weekdays',
        specialFestivals: 'Special / Festivals',
        holyMassTimings: 'Holy Mass Timings',
        loadingMassTimings: 'Loading mass timings...',
        noTimingsFound: 'No mass timings found for the selected filter.',
        importantNotes: '📌 Important Notes',
        arriveEarly: 'Please arrive 10 minutes before the scheduled time',
        confessionAvailable: 'Confession is available 30 minutes before each mass',
        specialTimings: 'Special mass timings may vary on feast days and holidays',
        contactOffice: 'For any queries, please contact the parish office',
    },
    notifications: {
        title: 'Announcements',
        type: 'Type',
        priority: 'Priority',
        parishAnnouncements: 'Parish Announcements',
        subtitle: 'Stay updated with the latest news and events from our parish',
        backToHome: '← Back to Home',
        all: 'All',
        urgent: 'Urgent',
        announcements: 'Announcements',
        events: 'Events',
        general: 'General',
        noAnnouncements: 'No announcements found.',
        loadingAnnouncements: 'Loading announcements...',
        allAnnouncements: 'All Announcements',
        priorityLabel: 'priority',
        expires: 'Expires',
    },
    bloodBank: {
        title: 'Blood Bank',
        subtitle: 'Donate blood, save lives - Join our parish blood donation community',
        registerAsDonor: 'Register as Blood Donor',
        searchDonors: 'Search Blood Donors',
        donorName: 'Donor Name',
        bloodGroup: 'Blood Group',
        age: 'Age',
        gender: 'Gender',
        lastDonation: 'Last Donation',
        available: 'Available',
        loadingBloodBank: 'Loading blood bank...',
        availableDonors: 'Available Donors',
        searchPlaceholder: 'Search by name or blood group...',
        closeForm: '✕ Close Form',
        registerAsDonorBtn: '+ Register as Donor',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        email: 'Email',
        dateOfBirth: 'Date of Birth',
        address: 'Address',
        lastDonationDate: 'Last Donation Date (optional)',
        yourFullName: 'Your full name',
        selectBloodGroup: 'Select blood group',
        yourEmail: 'email@example.com',
        yourFullAddress: 'Your full address',
        selectGender: 'Select gender',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        registering: 'Registering...',
        filterByBloodGroup: 'Filter by Blood Group',
        all: 'All',
        noDonorsFound: 'No donors found matching your criteria.',
        years: 'years',
        phone: 'Phone',
        addressLabel: 'Address',
    },
    familyUnits: {
        title: 'Family Units',
        subtitle: 'Connecting our parish community - Explore families across all units',
        familyDirectory: 'Family Directory',
        familyName: 'Family Name',
        headOfFamily: 'Head of Family',
        parishUnit: 'Parish Unit',
        members: 'Members',
        loadingDirectory: 'Loading family directory...',
        totalFamilies: 'Total Families',
        totalMembers: 'Total Members',
        maleMembers: 'Male Members',
        femaleMembers: 'Female Members',
        searchPlaceholder: 'Search by family name, head, address, or member name...',
        allUnits: 'All Units',
        showing: 'Showing',
        of: 'of',
        families: 'families',
        noFamiliesFound: '👨‍👩‍👧‍👦 No families found',
        for: 'for',
        head: 'Head',
        member: 'member',
        familyMembers: 'Family Members',
        years: 'years',
    },
    gallery: {
        title: 'Gallery',
        subtitle: 'Capturing moments of faith, fellowship, and celebration',
        categories: 'Categories',
        all: 'All',
        photoGallery: 'Photo Gallery',
        loadingGallery: 'Loading gallery...',
        noImagesFound: '📷 No images found in this category',
        showing: 'Showing',
        of: 'of',
        images: 'images',
        in: 'in',
        navigationHint: 'Use arrow keys ← → to navigate, ESC to close',
    },
    documents: {
        title: 'Documents',
        subtitle: 'Download bulletins, forms, newsletters, and important parish documents',
        category: 'Category',
        downloadDate: 'Upload Date',
        download: 'Download',
        churchDocuments: 'Church Documents',
        loadingDocuments: 'Loading documents...',
        searchPlaceholder: 'Search documents by title or description...',
        allDocuments: 'All Documents',
        noDocumentsFound: '📭 No documents found',
        for: 'for',
        showing: 'Showing',
        of: 'of',
        document: 'document',
        documents: 'documents',
    },
    news: {
        title: 'News',
        readMore: 'Read More',
        publishedOn: 'Published on',
        views: 'Views',
        latestNewsEvents: 'Latest News & Events',
        stayUpdated: 'Stay updated with the latest happenings in our parish',
        pinned: 'Pinned',
        viewAllNews: 'View All News & Events',
    },
    committee: {
        subtitle: 'Meet the dedicated leaders serving our parish community',
        noMembers: 'No committee members found.',
    },
    prayerRequest: {
        title: 'Prayer Request',
        subtitle: 'Submit your prayer intentions and our parish community will pray for you',
        howItWorks: '🙏 How It Works',
        shareIntention: 'Share your prayer intention with us',
        reviewedFirst: 'All requests are reviewed before being shared',
        anonymousOption: 'Check "Anonymous" if you prefer privacy',
        communityPrays: 'Our community will unite in prayer for your needs',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        prayerRequestLabel: 'Prayer Request',
        enterFullName: 'Enter your full name',
        enterEmail: 'your.email@example.com',
        enterPhone: '9876543210',
        sharePrayerIntention: 'Please share your prayer intention... (minimum 10 characters)',
        characters: 'characters',
        submitAnonymously: 'Submit anonymously (your name won\'t be displayed publicly)',
        submitPrayerRequest: '🙏 Submit Prayer Request',
        submitting: 'Submitting...',
        successMessage: 'Your prayer request has been submitted successfully! We will pray for you.',
        errorMessage: 'Failed to submit prayer request. Please try again.',
        networkError: 'Network error. Please check your connection and try again.',
        nameRequired: 'Name is required',
        nameMinLength: 'Name must be at least 2 characters',
        emailRequired: 'Email is required',
        validEmail: 'Please enter a valid email address',
        phoneRequired: 'Phone number is required',
        validPhone: 'Please enter a valid 10-digit phone number',
        requestRequired: 'Prayer request is required',
        requestMinLength: 'Please provide more details (at least 10 characters)',
        requestMaxLength: 'Prayer request is too long (maximum 1000 characters)',
    },
    thanksgiving: {
        title: 'Thanksgiving',
        subtitle: 'Share your blessings and gratitude with our community',
        thankYouGod: 'Thank You, God!',
        shareTestimony: 'Share your testimony of God\'s blessings',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        thanksgivingMessage: 'Thanksgiving Message',
        enterName: 'Enter your full name',
        enterEmail: 'your.email@example.com',
        enterPhone: '9876543210',
        shareTestimonyText: 'Share how God has blessed you...',
        submitAnonymously: 'Submit anonymously',
        submitThanksgiving: '🙌 Submit Thanksgiving',
        submitting: 'Submitting...',
        successMessage: 'Your thanksgiving has been shared! Glory to God!',
        errorMessage: 'Failed to submit. Please try again.',
    },
    venda: {
        title: 'Venda (Offerings)',
        subtitle: 'Support our parish through your generous offerings',
        selectOffering: 'Select Offering Type',
        generalOffering: 'General Offering',
        massOffering: 'Mass Offering',
        buildingFund: 'Building Fund',
        charityFund: 'Charity Fund',
        amount: 'Amount',
        enterAmount: 'Enter amount in ₹',
        donorName: 'Donor Name',
        enterDonorName: 'Enter your name',
        phoneNumber: 'Phone Number',
        enterPhone: '9876543210',
        emailAddress: 'Email Address (Optional)',
        enterEmail: 'your.email@example.com',
        purposeOptional: 'Purpose (Optional)',
        enterPurpose: 'Specify the purpose of this offering',
        proceedToPayment: '₹ Proceed to Payment',
        processing: 'Processing...',
    },
    common: {
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        noData: 'No data available',
        required: '*',
    },
};

// Malayalam Translations
const mlTranslations = {
    nav: {
        home: 'ഹോം',
        massTimings: 'കുർബാന സമയം',
        services: 'സേവനങ്ങൾ',
        community: 'സമൂഹം',
        about: 'ഞങ്ങളെക്കുറിച്ച്',
        contact: 'ബന്ധപ്പെടുക',
        prayerRequest: 'പ്രാർത്ഥനാ അപേക്ഷ',
        thanksgiving: 'നന്ദി പ്രകടനം',
        venda: 'വെണ്ട (കാഴ്ചകൾ)',
        bloodBank: 'രക്തബാങ്ക്',
        familyUnits: 'കുടുംബ ഡയറക്ടറി',
        gallery: 'ഗാലറി',
        documents: 'രേഖകൾ',
        brandName: 'നമ്മുടെ ഇടവക',
    },
    home: {
        heroTitle: 'ഞങ്ങളുടെ ഇടവകയിലേക്ക് സ്വാഗതം',
        heroSubtitle: 'വിശ്വാസം, പ്രത്യാശ, സ്നേഹം എന്നിവയുടെ സമൂഹം',
        bibleVerse1: '"ദൈവം ലോകത്തെ ഇത്ര സ്നേഹിച്ചു" - യോഹന്നാൻ 3:16',
        bibleVerse2: '"ഞാൻ വഴിയും സത്യവും ജീവനും ആകുന്നു" - യോഹന്നാൻ 14:6',
        bibleVerse3: '"ഞാൻ നിങ്ങളെ സ്നേഹിച്ചതുപോലെ നിങ്ങളും പരസ്പരം സ്നേഹിക്കുക" - യോഹന്നാൻ 13:34',
        quickLinksTitle: 'പെട്ടെന്നുള്ള ലിങ്കുകൾ',
        prayerRequestTitle: 'പ്രാർത്ഥനാ അപേക്ഷ',
        prayerRequestDesc: 'നിങ്ങളുടെ പ്രാർത്ഥനാ ഉദ്ദേശ്യങ്ങൾ സമർപ്പിക്കുക, ഞങ്ങൾ നിങ്ങൾക്കായി പ്രാർത്ഥിക്കും',
        thanksgivingTitle: 'നന്ദി പ്രകടനം',
        thanksgivingDesc: 'നിങ്ങളുടെ അനുഗ്രഹങ്ങളും നന്ദിയും ഞങ്ങളുടെ സമൂഹവുമായി പങ്കിടുക',
        vendaTitle: 'വെണ്ട (കാഴ്ചകൾ)',
        vendaDesc: 'നിങ്ങളുടെ ഉദാരമായ കാഴ്ചകളിലൂടെ ഇടവകയെ പിന്തുണയ്ക്കുക',
        latestNewsTitle: 'ഏറ്റവും പുതിയ വാർത്തകൾ',
        managingCommitteeTitle: 'നടത്തിപ്പ് സമിതി',
        ourChurchesTitle: 'നമ്മുടെ പള്ളികൾ',
        ourServicesTitle: 'നമ്മുടെ സേവനങ്ങൾ',
        latestAnnouncementsTitle: 'ഏറ്റവും പുതിയ അറിയിപ്പുകൾ',
        joinCommunityTitle: 'ഞങ്ങളുടെ സമൂഹത്തിൽ ചേരുക',
        joinCommunityDesc: 'ഞങ്ങളുടെ സ്നേഹനിർഭരമായ ഇടവക കുടുംബത്തിന്റെ ഭാഗമാകൂ. ഇന്ന് ഞങ്ങളുമായി ബന്ധപ്പെടുക!',
        holyMassTitle: 'വി. കുർബാന',
        holyMassDesc: 'ദിവസേനയും ഞായറാഴ്ചയും കുർബാന സമയങ്ങൾ',
        bloodBankTitle: 'രക്തബാങ്ക്',
        bloodBankDesc: 'രക്തദാതാവായി രജിസ്റ്റർ ചെയ്യുക',
        galleryTitle: 'ഗാലറി',
        galleryDesc: 'ഞങ്ങളുടെ പള്ളി പരിപാടികളും പ്രവർത്തനങ്ങളും കാണുക',
        familyUnitsTitle: 'കുടുംബ ഡയറക്ടറി',
        familyUnitsDesc: 'ഇടവക കുടുംബ ഡയറക്ടറി',
        loadingChurches: 'പള്ളികൾ ലോഡ് ചെയ്യുന്നു...',
        address: 'വിലാസം',
        phone: 'ഫോൺ',
        email: 'ഇമെയിൽ',
    },
    buttons: {
        submitRequest: 'അപേക്ഷ സമർപ്പിക്കുക',
        shareThanksgiving: 'നന്ദി പങ്കിടുക',
        makeOffering: 'കാഴ്ച നൽകുക',
        learnMore: 'കൂടുതൽ അറിയുക',
        viewSchedule: 'ഷെഡ്യൂൾ കാണുക',
        registerNow: 'ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക',
        viewGallery: 'ഗാലറി കാണുക',
        viewDirectory: 'ഡയറക്ടറി കാണുക',
        viewAllAnnouncements: 'എല്ലാ അറിയിപ്പുകളും കാണുക',
        contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
        submit: 'സമർപ്പിക്കുക',
        cancel: 'റദ്ദാക്കുക',
    },
    about: {
        title: 'ഞങ്ങളുടെ ഇടവകയെക്കുറിച്ച്',
        ourHistory: 'ഞങ്ങളുടെ ചരിത്രം',
        ourMission: 'ഞങ്ങളുടെ ദൗത്യം',
        ourVision: 'ഞങ്ങളുടെ കാഴ്ചപ്പാട്',
        ourChurches: 'നമ്മുടെ പള്ളികൾ',
        ourTeam: 'ഞങ്ങളുടെ ടീം',
        heroSubtitle: '1950 മുതൽ വിശ്വാസം, പ്രത്യാശ, സ്നേഹം എന്നിവയുമായി ഞങ്ങളുടെ സമൂഹത്തെ സേവിക്കുന്നു',
        storyPara1: 'വിശ്വാസത്തിൽ വളരാനും മറ്റുള്ളവരെ സേവിക്കാനുമുള്ള സ്വാഗതാർഹമുള്ള സമൂഹം സൃഷ്ടിക്കുക എന്ന ദൃഷ്ടിയോടെ 1950-ൽ ഞങ്ങളുടെ ഇടവക സ്ഥാപിച്ചു. ദശാബ്ദങ്ങളിലൂടെ, ഞങ്ങൾ ഒരു ചെറിയ സമ്മേളനത്തിൽ നിന്ന് ആരാധന, സഹഭാഗിത്വം, സേവനം എന്നിവയ്ക്ക് സമർപ്പിച്ച വിശ്വാസികളുടെ ചൈതന്യപൂർണ്ണമായ സമൂഹമായി വളർന്നു.',
        storyPara2: 'ഇന്ന്, ഞങ്ങൾ ഞങ്ങളുടെ പരമ്പരാഗതങ്ങളെ ആദരിക്കുന്നതോടൊപ്പം ഞങ്ങളുടെ സമൂഹത്തെ സേവിക്കുന്നതിനും ക്രിസ്തുവിന്റെ സ്നേഹം പങ്കിടുന്നതിനും പുതിയ വഴികൾ സ്വീകരിക്കുന്നു.',
        joinUsSunday: 'ഈ ഞായറാഴ്ച ഞങ്ങളോട് ചേരുക',
        experienceWorship: 'ആരാധന, സഹഭാഗിത്വം, സമൂഹം എന്നിവ ഞങ്ങളുമായി അനുഭവിക്കുക!',
        backToHome: 'ഹോം പേജിലേക്ക് മടങ്ങുക',
    },
    contact: {
        title: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
        getInTouch: 'ബന്ധപ്പെടുക',
        heroSubtitle: 'നിങ്ങളിൽ നിന്ന് കേൾക്കാൻ ഞങ്ങൾ ആഗ്രഹിക്കുന്നു. ഞങ്ങളുടെ ഇടവക സമൂഹവുമായി ബന്ധപ്പെടുക!',
        introText: 'ഇനിപ്പറയുന്ന ഏതെങ്കിലും മാർഗ്ഗത്തിലൂടെ ഞങ്ങളെ ബന്ധപ്പെടാൻ മടിക്കേണ്ടതില്ല. ഞങ്ങൾ നിങ്ങളെ സേവിക്കാൻ ഇവിടെയുണ്ട്!',
        mainChurchAddress: 'മുഖ്യ പള്ളിയുടെ വിലാസം',
        officeHours: 'ഓഫീസ് സമയം',
        massTimings: 'കുർബാന സമയം',
        name: 'പേര്',
        email: 'ഇമെയിൽ',
        phone: 'ഫോൺ',
        message: 'സന്ദേശം',
        subject: 'വിഷയം',
        send: 'സന്ദേശം അയയ്ക്കുക',
        sending: 'അയയ്ക്കുന്നു...',
        sendMessageBtn: '✉️ സന്ദേശം അയയ്ക്കുക',
        thankYouMessage: 'നിങ്ങളുടെ സന്ദേശത്തിന് നന്ദി! ഞങ്ങൾ ഉടനെ മറുപടി നൽകും.',
        fillAllFields: 'എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക',
        validEmail: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക',
        submitFailed: 'ഫോം സമർപ്പിക്കുന്നത് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
        yourFullName: 'നിങ്ങളുടെ പൂർണ്ണ നാമം',
        yourEmail: 'നിങ്ങളുടെ.ഇമെയിൽ@example.com',
        whatRegarding: 'ഇത് എന്തിനെക്കുറിച്ചാണ്?',
        typeMessage: 'നിങ്ങളുടെ സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
        findUsMap: 'മാപ്പിൽ ഞങ്ങളെ കണ്ടെത്തുക',
        visitUs: 'കേരളത്തിലെ കൊച്ചിയിലെ ഞങ്ങളുടെ പ്രധാന പള്ളി സ്ഥലത്ത് ഞങ്ങളെ സന്ദർശിക്കുക',
        mapNotLoading: 'മാപ്പ് ലോഡ് ആകുന്നില്ലേ? ഇത് പരസ്യ തടയൽ കാരണമായിരിക്കാം.',
        openGoogleMaps: 'Google മാപ്പിൽ തുറക്കുക',
        otherChurches: 'ഞങ്ങളുടെ മറ്റ് പള്ളികൾ',
        address: 'വിലാസം',
        sundayMass: 'ഞായർ കുർബാന',
        office: 'ഓഫീസ്',
        father: 'ഫാദർ',
        emergency: 'അടിയന്തിരം',
        mondayFriday: 'തിങ്കൾ - വെള്ളി',
        saturday: 'ശനി',
        sunday: 'ഞായർ',
        closedMassTimes: 'അടച്ചിരിക്കുന്നു (കുർബാന സമയം മാത്രം)',
        lunchBreak: 'ഉച്ചഭക്ഷണ ഇടവേള',
        weekdays: 'പ്രവൃത്തി ദിവസങ്ങൾ',
        sundays: 'ഞായറാഴ്ചകൾ',
        viewAllTimings: 'എല്ലാ സമയങ്ങളും കാണുക',
        sendUsMessage: 'ഞങ്ങൾക്ക് ഒരു സന്ദേശം അയയ്ക്കുക',
    },
    massTimings: {
        title: 'കുർബാന സമയം',
        subtitle: 'നമ്മുടെ ഇടവക പള്ളികളിൽ വിശുദ്ധ കുർബാന ആഘോഷത്തിൽ ഞങ്ങളോടൊപ്പം ചേരുക',
        selectChurch: 'പള്ളി തിരഞ്ഞെടുക്കുക',
        allChurches: 'എല്ലാ പള്ളികളും',
        day: 'ദിവസം',
        time: 'സമയം',
        language: 'ഭാഷ',
        type: 'തരം',
        allMasses: 'എല്ലാ കുർബാനകളും',
        sundays: 'ഞായറാഴ്ചകൾ',
        weekdays: 'പ്രവൃത്തി ദിവസങ്ങൾ',
        specialFestivals: 'പ്രത്യേക / ഉത്സവങ്ങൾ',
        holyMassTimings: 'വിശുദ്ധ കുർബാന സമയം',
        loadingMassTimings: 'കുർബാന സമയങ്ങൾ ലോഡ് ചെയ്യുന്നു...',
        noTimingsFound: 'തിരഞ്ഞെടുത്ത ഫിൽട്ടറിന് കുർബാന സമയങ്ങൾ കണ്ടെത്തിയില്ല.',
        importantNotes: '📌 പ്രധാന കുറിപ്പുകൾ',
        arriveEarly: 'നിശ്ചിത സമയത്തിന് 10 മിനിറ്റ് മുമ്പ് എത്തുക',
        confessionAvailable: 'ഓരോ കുർബാനയ്ക്കും 30 മിനിറ്റ് മുമ്പ് കുമ്പസാരം ലഭ്യമാണ്',
        specialTimings: 'തിരുനാളുകളിലും അവധി ദിവസങ്ങളിലും പ്രത്യേക കുർബാന സമയം വ്യത്യാസപ്പെടാം',
        contactOffice: 'എന്തെങ്കിലും ചോദ്യങ്ങൾക്ക്, ഇടവക ഓഫീസുമായി ബന്ധപ്പെടുക',
    },
    notifications: {
        title: 'അറിയിപ്പുകൾ',
        type: 'തരം',
        priority: 'മുൻഗണന',
        parishAnnouncements: 'ഇടവക അറിയിപ്പുകൾ',
        subtitle: 'ഞങ്ങളുടെ ഇടവകയിൽ നിന്നുള്ള ഏറ്റവും പുതിയ വാർത്തകളും പരിപാടികളും അറിയുക',
        backToHome: '← ഹോമിലേക്ക് മടങ്ങുക',
        all: 'എല്ലാം',
        urgent: 'അടിയന്തിരം',
        announcements: 'അറിയിപ്പുകൾ',
        events: 'പരിപാടികൾ',
        general: 'പൊതു',
        noAnnouncements: 'അറിയിപ്പുകൾ കണ്ടെത്തിയില്ല.',
        loadingAnnouncements: 'അറിയിപ്പുകൾ ലോഡ് ചെയ്യുന്നു...',
        allAnnouncements: 'എല്ലാ അറിയിപ്പുകളും',
        priorityLabel: 'മുൻഗണന',
        expires: 'കാലഹരണപ്പെടുന്നത്',
    },
    bloodBank: {
        title: 'രക്തബാങ്ക്',
        subtitle: 'രക്തം ദാനം ചെയ്യുക, ജീവൻ രക്ഷിക്കുക - ഞങ്ങളുടെ ഇടവക രക്തദാന സമൂഹത്തിൽ ചേരുക',
        registerAsDonor: 'രക്തദാതാവായി രജിസ്റ്റർ ചെയ്യുക',
        searchDonors: 'രക്തദാതാക്കളെ തിരയുക',
        donorName: 'ദാതാവിന്റെ പേര്',
        bloodGroup: 'രക്തഗ്രൂപ്പ്',
        age: 'പ്രായം',
        gender: 'ലിംഗം',
        lastDonation: 'അവസാന ദാനം',
        available: 'ലഭ്യമാണ്',
        loadingBloodBank: 'രക്തബാങ്ക് ലോഡ് ചെയ്യുന്നു...',
        availableDonors: 'ലഭ്യമായ ദാതാക്കൾ',
        searchPlaceholder: 'പേര് അല്ലെങ്കിൽ രക്തഗ്രൂപ്പ് ഉപയോഗിച്ച് തിരയുക...',
        closeForm: '✕ ഫോം അടയ്ക്കുക',
        registerAsDonorBtn: '+ ദാതാവായി രജിസ്റ്റർ ചെയ്യുക',
        fullName: 'പൂർണ്ണ നാമം',
        phoneNumber: 'ഫോൺ നമ്പർ',
        email: 'ഇമെയിൽ',
        dateOfBirth: 'ജനനത്തീയതി',
        address: 'വിലാസം',
        lastDonationDate: 'അവസാന ദാന തീയതി (ഓപ്ഷണൽ)',
        yourFullName: 'നിങ്ങളുടെ പൂർണ്ണ നാമം',
        selectBloodGroup: 'രക്തഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക',
        yourEmail: 'email@example.com',
        yourFullAddress: 'നിങ്ങളുടെ പൂർണ്ണ വിലാസം',
        selectGender: 'ലിംഗം തിരഞ്ഞെടുക്കുക',
        male: 'പുരുഷൻ',
        female: 'സ്ത്രീ',
        other: 'മറ്റുള്ളവ',
        registering: 'രജിസ്റ്റർ ചെയ്യുന്നു...',
        filterByBloodGroup: 'രക്തഗ്രൂപ്പ് അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
        all: 'എല്ലാം',
        noDonorsFound: 'നിങ്ങളുടെ മാനദണ്ഡവുമായി യോജിക്കുന്ന ദാതാക്കളെ കണ്ടെത്തിയില്ല.',
        years: 'വയസ്സ്',
        phone: 'ഫോൺ',
        addressLabel: 'വിലാസം',
    },
    familyUnits: {
        title: 'കുടുംബ യൂണിറ്റുകൾ',
        subtitle: 'നമ്മുടെ ഇടവക സമൂഹത്തെ ബന്ധിപ്പിക്കുന്നു - എല്ലാ യൂണിറ്റുകളിലെയും കുടുംബങ്ങൾ അന്വേഷിക്കുക',
        familyDirectory: 'കുടുംബ ഡയറക്ടറി',
        familyName: 'കുടുംബ നാമം',
        headOfFamily: 'കുടുംബനാഥൻ',
        parishUnit: 'ഇടവക യൂണിറ്റ്',
        members: 'അംഗങ്ങൾ',
        loadingDirectory: 'കുടുംബ ഡയറക്ടറി ലോഡ് ചെയ്യുന്നു...',
        totalFamilies: 'ആകെ കുടുംബങ്ങൾ',
        totalMembers: 'ആകെ അംഗങ്ങൾ',
        maleMembers: 'പുരുഷ അംഗങ്ങൾ',
        femaleMembers: 'സ്ത്രീ അംഗങ്ങൾ',
        searchPlaceholder: 'കുടുംബ നാമം, തലവൻ, വിലാസം അല്ലെങ്കിൽ അംഗത്തിന്റെ പേര് ഉപയോഗിച്ച് തിരയുക...',
        allUnits: 'എല്ലാ യൂണിറ്റുകളും',
        showing: 'കാണിക്കുന്നത്',
        of: 'ൽ',
        families: 'കുടുംബങ്ങൾ',
        noFamiliesFound: '👨‍👩‍👧‍👦 കുടുംബങ്ങൾ കണ്ടെത്തിയില്ല',
        for: 'എന്നതിന്',
        head: 'തലവൻ',
        member: 'അംഗം',
        familyMembers: 'കുടുംബാംഗങ്ങൾ',
        years: 'വയസ്സ്',
    },
    gallery: {
        title: 'ഗാലറി',
        subtitle: 'വിശ്വാസം, കൂട്ടായ്മ, ആഘോഷം എന്നിവയുടെ നിമിഷങ്ങൾ പകർത്തുന്നു',
        categories: 'വിഭാഗങ്ങൾ',
        all: 'എല്ലാം',
        photoGallery: 'ഫോട്ടോ ഗാലറി',
        loadingGallery: 'ഗാലറി ലോഡ് ചെയ്യുന്നു...',
        noImagesFound: '📷 ഈ വിഭാഗത്തിൽ ചിത്രങ്ങൾ കണ്ടെത്തിയില്ല',
        showing: 'കാണിക്കുന്നത്',
        of: 'ൽ',
        images: 'ചിത്രങ്ങൾ',
        in: 'ൽ',
        navigationHint: 'നാവിഗേറ്റ് ചെയ്യാൻ ← → ആരോ കീകൾ ഉപയോഗിക്കുക, അടയ്ക്കാൻ ESC',
    },
    documents: {
        title: 'രേഖകൾ',
        subtitle: 'ബുള്ളറ്റിനുകൾ, ഫോമുകൾ, വാർത്താക്കുറിപ്പുകൾ, പ്രധാന ഇടവക രേഖകൾ ഡൗൺലോഡ് ചെയ്യുക',
        category: 'വിഭാഗം',
        downloadDate: 'അപ്‌ലോഡ് തീയതി',
        download: 'ഡൗൺലോഡ്',
        churchDocuments: 'പള്ളി രേഖകൾ',
        loadingDocuments: 'രേഖകൾ ലോഡ് ചെയ്യുന്നു...',
        searchPlaceholder: 'ശീർഷകം അല്ലെങ്കിൽ വിവരണം ഉപയോഗിച്ച് രേഖകൾ തിരയുക...',
        allDocuments: 'എല്ലാ രേഖകളും',
        noDocumentsFound: '📭 രേഖകൾ കണ്ടെത്തിയില്ല',
        for: 'എന്നതിന്',
        showing: 'കാണിക്കുന്നത്',
        of: 'ൽ',
        document: 'രേഖ',
        documents: 'രേഖകൾ',
    },
    news: {
        title: 'വാർത്തകൾ',
        readMore: 'കൂടുതൽ വായിക്കുക',
        publishedOn: 'പ്രസിദ്ധീകരിച്ചത്',
        views: 'കാഴ്ചകൾ',
        latestNewsEvents: 'ഏറ്റവും പുതിയ വാർത്തകളും പരിപാടികളും',
        stayUpdated: 'ഞങ്ങളുടെ ഇടവകയിലെ ഏറ്റവും പുതിയ സംഭവങ്ങളുമായി കാലികമായി തുടരുക',
        pinned: 'പിൻ ചെയ്തത്',
        viewAllNews: 'എല്ലാ വാർത്തകളും പരിപാടികളും കാണുക',
    },
    committee: {
        subtitle: 'ഞങ്ങളുടെ ഇടവക സമൂഹത്തെ സേവിക്കുന്ന സമർപ്പിത നേതാക്കളെ കണ്ടുമുട്ടുക',
        noMembers: 'സമിതി അംഗങ്ങളെ കണ്ടെത്തിയില്ല.',
    },
    prayerRequest: {
        title: 'പ്രാർത്ഥനാ അപേക്ഷ',
        subtitle: 'നിങ്ങളുടെ പ്രാർത്ഥനാ ഉദ്ദേശ്യങ്ങൾ സമർപ്പിക്കുക, ഞങ്ങളുടെ ഇടവക സമൂഹം നിങ്ങൾക്കായി പ്രാർത്ഥിക്കും',
        howItWorks: '🙏 ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
        shareIntention: 'നിങ്ങളുടെ പ്രാർത്ഥനാ ഉദ്ദേശ്യം ഞങ്ങളുമായി പങ്കിടുക',
        reviewedFirst: 'എല്ലാ അപേക്ഷകളും പങ്കിടുന്നതിനു മുമ്പ് അവലോകനം ചെയ്യപ്പെടും',
        anonymousOption: 'സ്വകാര്യത ആഗ്രഹിക്കുന്നുവെങ്കിൽ "അജ്ഞാതമായി" തിരഞ്ഞെടുക്കുക',
        communityPrays: 'നമ്മുടെ സമൂഹം നിങ്ങളുടെ ആവശ്യങ്ങൾക്കായി പ്രാർത്ഥനയിൽ ഒന്നിക്കും',
        fullName: 'മുഴുവൻ പേര്',
        emailAddress: 'ഇമെയിൽ വിലാസം',
        phoneNumber: 'ഫോൺ നമ്പർ',
        prayerRequestLabel: 'പ്രാർത്ഥനാ അപേക്ഷ',
        enterFullName: 'മുഴുവൻ പേര് നൽകുക',
        enterEmail: 'നിങ്ങളുടെ.ഇമെയിൽ@example.com',
        enterPhone: '9876543210',
        sharePrayerIntention: 'നിങ്ങളുടെ പ്രാർത്ഥനാ ഉദ്ദേശ്യം പങ്കിടുക... (കുറഞ്ഞത് 10 അക്ഷരങ്ങൾ)',
        characters: 'അക്ഷരങ്ങൾ',
        submitAnonymously: 'അജ്ഞാതമായി സമർപ്പിക്കുക (നിങ്ങളുടെ പേര് പരസ്യമായി പ്രദർശിപ്പിക്കില്ല)',
        submitPrayerRequest: '🙏 പ്രാർത്ഥനാ അപേക്ഷ സമർപ്പിക്കുക',
        submitting: 'സമർപ്പിക്കുന്നു...',
        successMessage: 'നിങ്ങളുടെ പ്രാർത്ഥനാ അപേക്ഷ വിജയകരമായി സമർപ്പിച്ചു! ഞങ്ങൾ നിങ്ങൾക്കായി പ്രാർത്ഥിക്കും.',
        errorMessage: 'പ്രാർത്ഥനാ അപേക്ഷ സമർപ്പിക്കുന്നത് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
        networkError: 'നെറ്റ്‌വർക്ക് പിശക്. നിങ്ങളുടെ കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
        nameRequired: 'പേര് ആവശ്യമാണ്',
        nameMinLength: 'പേര് കുറഞ്ഞത് 2 അക്ഷരങ്ങളുള്ളതായിരിക്കണം',
        emailRequired: 'ഇമെയിൽ ആവശ്യമാണ്',
        validEmail: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക',
        phoneRequired: 'ഫോൺ നമ്പർ ആവശ്യമാണ്',
        validPhone: 'സാധുവായ 10 അക്ക ഫോൺ നമ്പർ നൽകുക',
        requestRequired: 'പ്രാർത്ഥനാ അപേക്ഷ ആവശ്യമാണ്',
        requestMinLength: 'കൂടുതൽ വിശദാംശങ്ങൾ നൽകുക (കുറഞ്ഞത് 10 അക്ഷരങ്ങൾ)',
        requestMaxLength: 'പ്രാർത്ഥനാ അപേക്ഷ വളരെ നീളമേറിയതാണ് (പരമാവധി 1000 അക്ഷരങ്ങൾ)',
    },
    thanksgiving: {
        title: 'നന്ദി പ്രകടനം',
        subtitle: 'നിങ്ങളുടെ അനുഗ്രഹങ്ങളും കൃതജ്ഞതയും ഞങ്ങളുടെ സമൂഹവുമായി പങ്കിടുക',
        thankYouGod: 'ദൈവമേ, നന്ദി!',
        shareTestimony: 'ദൈവത്തിന്റെ അനുഗ്രഹങ്ങളുടെ നിങ്ങളുടെ സാക്ഷ്യം പങ്കിടുക',
        fullName: 'മുഴുവൻ പേര്',
        emailAddress: 'ഇമെയിൽ വിലാസം',
        phoneNumber: 'ഫോൺ നമ്പർ',
        thanksgivingMessage: 'നന്ദി സന്ദേശം',
        enterName: 'മുഴുവൻ പേര് നൽകുക',
        enterEmail: 'നിങ്ങളുടെ.ഇമെയിൽ@example.com',
        enterPhone: '9876543210',
        shareTestimonyText: 'ദൈവം നിങ്ങളെ എങ്ങനെ അനുഗ്രഹിച്ചുവെന്ന് പങ്കിടുക...',
        submitAnonymously: 'അജ്ഞാതമായി സമർപ്പിക്കുക',
        submitThanksgiving: '🙌 നന്ദി സമർപ്പിക്കുക',
        submitting: 'സമർപ്പിക്കുന്നു...',
        successMessage: 'നിങ്ങളുടെ നന്ദി പങ്കിട്ടു! ദൈവത്തിന് മഹത്വം!',
        errorMessage: 'സമർപ്പിക്കുന്നത് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    },
    venda: {
        title: 'വെണ്ട (കാഴ്ചകൾ)',
        subtitle: 'നിങ്ങളുടെ ഉദാരമായ കാഴ്ചകളിലൂടെ ഇടവകയെ പിന്തുണയ്ക്കുക',
        selectOffering: 'കാഴ്ച തരം തിരഞ്ഞെടുക്കുക',
        generalOffering: 'പൊതു കാഴ്ച',
        massOffering: 'കുർബാന കാഴ്ച',
        buildingFund: 'കെട്ടിട ഫണ്ട്',
        charityFund: 'ചാരിറ്റി ഫണ്ട്',
        amount: 'തുക',
        enterAmount: '₹യിൽ തുക നൽകുക',
        donorName: 'ദാതാവിന്റെ പേര്',
        enterDonorName: 'നിങ്ങളുടെ പേര് നൽകുക',
        phoneNumber: 'ഫോൺ നമ്പർ',
        enterPhone: '9876543210',
        emailAddress: 'ഇമെയിൽ വിലാസം (ഓപ്ഷണൽ)',
        enterEmail: 'നിങ്ങളുടെ.ഇമെയിൽ@example.com',
        purposeOptional: 'ഉദ്ദേശ്യം (ഓപ്ഷണൽ)',
        enterPurpose: 'ഈ കാഴ്ചയുടെ ഉദ്ദേശ്യം വ്യക്തമാക്കുക',
        proceedToPayment: '₹ പേയ്‌മെന്റിലേക്ക് പോകുക',
        processing: 'പ്രോസസ് ചെയ്യുന്നു...',
    },
    common: {
        loading: 'ലോഡ് ചെയ്യുന്നു...',
        error: 'പിശക്',
        success: 'വിജയം',
        noData: 'ഡാറ്റ ലഭ്യമല്ല',
        required: '*',
    },
};
